pipeline {
    agent any

    tools {
        maven 'Maven - 3.9.9'   // Use your Maven name from Jenkins (Manage Jenkins → Global Tool Config)
    }

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/Ganeshaprasad/cucumber-ninja'  // Replace with your repo
            }
        }

        stage('Build & Test') {
            steps {
                bat 'mvn clean test'
            }
        }

        stage('Archive Reports') {
            steps {
                archiveArtifacts artifacts: 'target/ExtentReport/*.html', allowEmptyArchive: true
                junit 'target/surefire-reports/*.xml'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
        success {
        echo 'Build Passed!'
        emailext (
            to: 'ganesha.prasad1996@gmail.com',
            subject: "Jenkins Job Success: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
            body: "Good news!\n\nThe Jenkins job ${env.JOB_NAME} #${env.BUILD_NUMBER} has passed.",
            attachLog: true
        )
    }
    failure {
        echo 'Build Failed!'
        emailext (
            to: 'ganesha.prasad1996@gmail.com',
            subject: "Jenkins Job FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
            body: "Alert!\n\nThe Jenkins job ${env.JOB_NAME} #${env.BUILD_NUMBER} has failed.",
            attachLog: true
        )
    }
    }
}
