pipeline {
    agent any

    tools {
        maven 'Maven - 3.9.9'   // Use your Maven name from Jenkins (Manage Jenkins → Global Tool Config)
    }
   triggers {
        cron('18 10 * * *')  // Runs every day at 10:18 PM
    }
    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/Ganeshaprasad/cucumber-ninja'  // Replace with your repo
            }
        }

        stage('Build & Test') {
            steps {
                bat 'mvn clean test'
            }
        }

        stage('Archive Reports') {
            steps {
                archiveArtifacts artifacts: 'target/ExtentReport/*.html', allowEmptyArchive: true
                junit 'target/surefire-reports/*.xml'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
        success {
        echo 'Build Passed!'
    }
    failure {
        echo 'Build Failed!'

    }
    }
}
